### ISSUE TITLE
Room Correction

### ISSUE THREAD

**Issue by jaakkopasanen** [jaakkopasanen/Impulcifer#13]
Room acoustics play huge role in how good the HRIR sounds. Impulcifer should be able equalize room's frequency response into a target listening curve. This implies handling of room impulse response measurement, calculating it's frequency response,creating inverse frequency response FIR filter and equalizing HRIR tracks with it.

Room measurement can have one channel, same number of channels as there are output speakers or double the number of output speakers. In case where there is only one channel in the room measurement that will be used for equalizing all of the head related impulse responses. If there are equal number to the output speakers then each measurement will be used for the respective speaker. Finally for room measurement files with double the output speaker count each channel in the room measurement file will correspond to one virtualized speak and ear pair.

Add `--room` parameter to Impulcifer which defaults to `{out_dir}/room.wav`. Add `--room_speakers` parameter to Impulcifer which tells which speakers each track or track pair in the file match. This is a list of speaker names and will be comma separated list in the CLI like: `"--room_speakers=FL,FR,RL,SL,SR,RR,C"`. If there are equal number of channel as there are output speakers then each item in the `--room_spaekers` list matches one channel in the file. If there are double the number of channels as there are output speakers then every even number (0, 2, ...) channel will be for left ear and odd number (1, 3, ...) channel for right ear. In this case each item in the `--room_speakers` list matches two consecutive channels in the room measurement file.

**Comment by rpx91** [comment]
Quick suggestion on this: it'd be ideal if Impulcifer could output two HRIR for HeSuVi - one with room correction and another without. It'd be good for A vs Bing in HeSuVi to show the power of the correction without having to run commands twice.

**Comment by jaakkopasanen** [comment]
Mostly implemented now. Doesn't work if some speaker-ear pairs have room measurement and some don't, this needs to be fixed.

Would be convenient to have support general room measurement which is not specific to any speaker-ear pair because those can be a pain to do. This would need to have the upper frequency limit at 1000 Hz. Also multiple recording at different points would be good, averaging should do the trick.

For some reason the 20 Hz to 30 Hz is not compensated properly and is down by 10 dB in the demo recordings. This would be good fix.

Mixed phase filter needs to be implemented. Perhaps from Python Open Room Correction project.

**Comment by rpx91** [comment]
Might be worth putting this in the documentation - a big benefit of measuring a real 5 or 7 channel system or setting up speakers around you. You only needed to place the measurement mics in two positions.
