### ISSUE TITLE
Measurement

### ISSUE THREAD

**Issue by jaakkopasanen** [jaakkopasanen/Impulcifer#17]
Implement measurement with interactive CLI.

**Comment by venkatesh63** [comment]
Smyth Research Realiser A16 (16 virtual Speakers) measurements files can i get. i tried demo but it was only 8 channels.please @jaakkopasanen if you can share 16 virtual Speakers files.

**Comment by jaakkopasanen** [comment]
@venkatesh63 I don't have 16 speaker measurement. Smyth Realiser A16 can decode Dolby Atmos so it can actually utilize those 16 speakers. In Windows however the only thing that can decode Atmos is Dolby Atmos for Headphones software. HeSuVi, EqualizerAPO or any video player is not compatible with more than 8 (7.1) channels. This is the reason why Impulcifer has been designed to work with 7 channel measurements and no more. Perhaps in the future there will be Atmos decoders for Windows and then I might add support for more than 7 channels in Impulcifer.

**Comment by venkatesh63** [comment]
@jaakkopasanen Thanks for replying me. Right now i'm using data/demo with HeSuVi and my virtualization was ssc_ny+.wav. it was quiet good for me to music and movies. can i get any files rather than data/demo because i don't have measurement gear.

**Comment by venkatesh63** [comment]
And again you said Atmos decoders for windows in future are making any scripting with this Impulcifer or can i assume alternate making software or application from you.

**Comment by jaakkopasanen** [comment]
I basically only have the measurements which are in the demo folder. It's made with mics in my ears in my apartment. I intend to measure other people as well and share those measurements in HeSuVi, but this might take some time.

I'm not sure I understood your second message. If Dolby or someone else releases a software on Windows which can decode Dolby Atmos, I might extend Impulcifer to support more than 7 speakers.

**Comment by venkatesh63** [comment]
ok fine then @jaakkopasanen

**Comment by jaakkopasanen** [comment]
An idea I had for measurement UX was to scan for any WAV files in the input directory that are any combination of the supported channel names such as: `FL,FR.wav` or `FC.wav` or `FL,FC,FR,SR,BR,BL,SL.wav`. Then I could implement a simple script which plays back one file (the sine sweep sequence) and writes a mic input to a WAV file. User gives the file name as a CLI argument like `--output=data/my_hrir/SR,BR.wav` when using a two channel sequence to record virtual side right and back right speakers. This script would be ran with different output file name as many times as needed.

**Comment by venkatesh63** [comment]
@jaakkopasanen i appreciate your measurement UX script. i want SR,BR.wav files.please give me attachments.

**Comment by jaakkopasanen** [comment]
@venkatesh63 If by an application you mean having a graphical user interface for the measurement process, then I intend to just that. It won't be a desktop software like HeSuVi but rather a webpage which doesn't require anything to be installed. This however will be a major effort and will be a long way into the future. I'll implement the measurement script so people can use that for the time being and don't have to mess around with Audacity.

**Comment by venkatesh63** [comment]
@jaakkopasanen When it will be complete your measurements.

**Comment by jaakkopasanen** [comment]
Measurement script has been implemented now. I still need to do testing and probably fix something but the recording functionality should be there.

Run it like this to play sweeps on left and right physical speakers.
```
python recorder.py --play="sweep-seg-FL,FR-stereo-6.15s-48000Hz-32bit-2.93Hz-24000Hz.wav" --record="data/my_hrir/FL,FR.wav"
```

Recorder uses default input and output sound devices but those can be selected with `--input_device` and `--output_device`. See `python recorder.py -h` for more info.

Impulcifer cannot yet read recording files with these names. That will be implemented next. Then comes the guide in wiki before I close this issue.

**Comment by jaakkopasanen** [comment]
Everything done!

Impulcifer reads recording files from the input folder and figures out the speaker order from the file names.

The measurement guide has been updated to use the recorder utility and project front page has a quick reference guide.
