### ISSUE TITLE
Sibilant/Bright Headphone Issue (DT990)

### ISSUE THREAD

**Issue by rpx91** [jaakkopasanen/Impulcifer#22]
I mentioned this on Head-Fi.

When using Headphone Compensation on the DT990 the horrible Siblant treble that headphone naturally has doesn't go away.

When using the no headphone compensation flag for HRIR calculation and instead, relying on Oratory's measurement source and computing a flat EQ via Auto EQ the sound is much better and no horrific treble.

I'm pretty sure this isn't a preference thing - it's not there in the original speaker/room. I also tried A vs Bing the headphone compensation between the DT990 and a Aurvana SE and the Aurvana has no such issue.

I believe the headphone compensation has a hard time with these sorts of issues. It might speak more to headphone selection or relying on GRAS measurements than a fix - but worth nothing.

I've uploaded my [headphone.wav here ](https://drive.google.com/drive/folders/1r-rdfL4-RQPv6uu7NNZcNkWu19TJsHAG?usp=sharing)

I've also included a channel ID check of a female human voice which makes the issue very clear.

And my computation of the flat EQ that works well

Edit: Added the full output from AutoEQ's flat calculation to the link too.

**Comment by jaakkopasanen** [comment]
This is certainly something I have found out myself too. I'm using Sennheiser HD 800 and to equalize that to Harman target a reduction at 6 kHz of 7.5 dB is required but the headphone compensation in Impulcifer has less than that. It might be that it's actually the diffuse field target which is required for HRTF headphone compensation and that would explain results with HD 800 to a degree. Another thing I noticed was that the bass roll off at 20 Hz according to headphone compensation measurement is 10 dB while only a couple of decibels should be enough.

One thing that we could try for starters is to do the headphone compensation measurement with EQ to harman target. So use equalization settings from AutoEQ or oratory1990 with EqualizerAPO while recording the exponential sine sweep with headphones. This EQ has to be disabled for speaker measurements but should be enabled when using the produced HRIR.

**Comment by rpx91** [comment]
Oh! Of course - I didn't think of that - fix the nasty headphone before measuring it.

Another round of listening to sine sweeps in my ears coming up for my collection of 4 headphones haha.

**Comment by jaakkopasanen** [comment]
If this turns out to be a valid solution the I could add functionality which bakes the equalization curve used for headphone compensation measurements into the HRIR.

**Comment by rpx91** [comment]
Sounds good, I'm going on holiday for a month from Saturday so I'll try it when I'm back.

Meanwhile I'll be able to use my theater setup from home in my Airbnb thanks to Impulcifer 😀

**Comment by jaakkopasanen** [comment]
Equalizing the headphone to Harman target during headphone compensation recording did not improve anything. I still implemented the eq baking so now it's a bit clearer how to use IEMs.

I lack ideas how to fix this issue. At least manual equalization of #14 should help but that is not going to be as convenient as having an algorithmic solution.

**Comment by rpx91** [comment]
I did a measurement today with the DT990 - I used --trend and the room correction. Not sure what's made the difference but even the DT990 sounds bang on now. The huge cups and openback really make it suitable for speaker virtualization

**Comment by jaakkopasanen** [comment]
I have ran a lot of experiments regarding headphone compensation and I'm quite confident that it works correctly. I certainly am not having problems with sibilance and yours seems to be solved as well. Should be close this issue?

**Comment by rpx91** [comment]
Yep, you can close.

Happy new year btw :-)
