### ISSUE TITLE
7.1 Channel Sweep

### ISSUE THREAD

**Issue by rpx91** [jaakkopasanen/Impulcifer#24]
The spinorama is great for when you have two speakers but it's so much quicker to just measure a pre-existing multi channel setup if you have one.

Could we get a sweep that outputs in 7 channels?

I tried to open up the dirac 7 channel impulse and paste in the sweeps - but Audacity confuses me because the first track appears in stereo and the rest are mono.

**Comment by jaakkopasanen** [comment]
Even better, you can generate it yourself. Just the way you want to.
```
python impulse_response_estimator.py --dir_path=data --fs=48000 --speakers=FL,FC,FR,SR,BR,BL,SL --tracks=7.1
```

**Comment by rpx91** [comment]
Awesome! I'm upgrading to 7.1.4 after a refurb so I won't ever need to get wires caught and spin on a bar stool again haha

**Comment by venkatesh63** [comment]
@rpx91 please share your 7.1.4 files if you can i will try.
