### ISSUE TITLE
Bluetooth Headphone Compensation - Lag?

### ISSUE THREAD

**Issue by rpx91** [jaakkopasanen/Impulcifer#26]
When compensating for bluetooth headphones - does the lag (192ms for my Bose 700) impact Impulcifer's calculations? Should you trim the recording by the lag value?

I'd prefer to do a compensation for BT headphones without using a wire because frequency response is typically different in passive vs BT modes.

**Comment by jaakkopasanen** [comment]
It's not going to affect Impulcifer. There is only 1ms of head in the impulse responses so there is nothing to cut. Bluetooth lag will be added after processing in EqualizerAPO so it's not going to affect the virtual speakers either. There will be lag but it's no different compared to listening to headphones without any DSP. So nothing to worry about.

**Comment by rpx91** [comment]
I figured it worked because my XM3's over BT worked fine, but I'm having a harder time with the Bose 700 - but I believe it's due to clamp force. I've just gotta get better at getting the mics to stay in place.
