### ISSUE TITLE
7.1 Surround FL Lower Delay

### ISSUE THREAD

**Issue by Shikamon** [jaakkopasanen/Impulcifer#27]
Greetings @jaakkopasanen ! I have recently found out about your project Impulcifer and I have to say it's pretty cool! I've been doing my own headphone equalizing journey for a good while now. I just received my own IEM in the mail yesterday just to try out your method. :)

I was successful in recording all 7 channels via doing the mono speaker method (as I only have one to work with at the moment), though I got an error regarding that the FL channel has a lower delay of the right ear compared to the left ear. Which is funny cause I checked my recordings by ear and it does seem ok for FL as I try to get it to be distinguished compared to SL. Is there something I'm doing wrong? I can upload my audacity project if you have the time to take a quick look. 

Doing this method is fun but super tedious when trying to get everything perfect (i.e. putting on the darn IEM's properly *ugh*). 

Thanks in advance and keep up the good work!! :D 

[7.1_Surround Sound_v2.zip](https://github.com/jaakkopasanen/Impulcifer/files/3608645/7.1_Surround.Sound_v2.zip)

**Comment by jaakkopasanen** [comment]
Hey, thanks for trying out Impulcifer and giving feedback. I really appreciate it.

I would need the data directory to be able to open that Audacity project. The `.aup` file itself is not enough.

I believe Impulcifer should not crash anymore if there are some oddities with delay but simply give you the warning. Did you manage to produce `hrir.wav` and `hesuvi.wav` and did you try them out how they sound like? Does it sound like the virtual front left (FL) speaker is at it's right spot 30 degrees to left in front of you or does it sound like it's on the right side?

**Comment by Shikamon** [comment]
Ok. Sorry about that! I'll just share a google drive link to my recording.wav file I have instead. 
Link:
[https://drive.google.com/file/d/1KVgqMQlNZ4gLuW-qT9gaTGPi6pMWOsRg/view?usp=sharing](url)

I did make the hrir.wav and hesuvi.wav files and they sound ok but it sounds pretty bad as the whole surround sounds shift to the right instead of the center. I'll attach my hesuvi.wav also if that helps any. :0

Link: [https://drive.google.com/file/d/1k6uAa9uresg-VAr0ITIeGJentXl837IT/view?usp=sharing](url)

**Comment by jaakkopasanen** [comment]
Thanks for sharing the recording file.

The peak detection algorithm didn't do it's job well enough. I improved it and now I'm not getting the warning anymore. Your FL measurement was correct but the algorithm detected a wrong peak from the left microphone data.

The HRIR balance does indeed sound like it's quite a lot on the right side. The graphs also show this. If you compare the frequency responses of FL-left and FR-right you'll notice that the FR-right has some 10 dB extra on both sides of 10 kHz. One thing that could cause this is nonidentical placement of the in-ear mics. Headphone compensation should take care of this normally. Did you do headphone compensation?

**Comment by Shikamon** [comment]
I have compensated my headphones (i.e. Status CB-1). I'll link that .wav file as well. :)
Link: https://drive.google.com/file/d/1k4TCcDsVomojPYcwSQwVV15iHw7lebp_/view?usp=sharing

And yeah I had a feeling you would mention the IEM balance. Which is funny because I was kinda suspicious of them being that way despite them having a flat frequency response. The IEM's I bought were the SP-TFB-2 binaural mic (https://www.soundprofessionals.com/cgi-bin/gold/item/SP-TFB-2). They're pretty nice but what I did was compared the left and right mic frequency response and noticed that they were not the same level. It was off by about 5 dB or so and I created a EQ filter of that difference to help balance things out. 
![SP-TFB-2 Imbalance](https://user-images.githubusercontent.com/55271169/64919425-73c74f80-d778-11e9-97df-dd2bb6313421.png)

Not only that, but I thought I could compare the overall frequency response to another measurement mic I own which is the Dayton Audio iMM-6 (http://www.daytonaudio.com/index.php/imm-6-idevice-calibrated-measurement-microphone.html). I trust this to be more correct as they give you a specific .cal file to use to compensate it based on the model number on the back of the metal case it comes in. The difference seems a bit similar on the mid range area but varies quite a bit in the high range:
![SP-TFB-2 vs Dayton iMM-6](https://user-images.githubusercontent.com/55271169/64919484-4b8c2080-d779-11e9-81d8-47ea75b602cd.png)

I might need to do this calibration measurement again as I think doing it in a free field setup might give a better result for the IEM compared to placing both mics near the left driver of my headphone. 

Anywho, I hope this wasn't too much of an information overload for you. Wanted to give you a clear picture of what I've done and found out on my end. :D

**Comment by jaakkopasanen** [comment]
Good stuff. I'll need to see what your headphone compensation recording does for the channel balance. Headphone compensation should fix any channel balance issues whether they are caused by mic placement, mics, mic preamp, adc or headphones.

I've been planning to do the same kind of calibration against calibrated measurement mic but haven't got to it yet because I only received UMIK-1 last week. This however should not affect the end result because the calibration is not needed. Headphone compensation equalizes frequency response of heaphones and mics alike.
