### ISSUE TITLE
Tensorflow Errors or Warnings

### ISSUE THREAD

**Issue by venkatesh63** [jaakkopasanen/Impulcifer#30]
python impulcifer.py --dir_path=data/demo --test_signal=data/sweep-6.15s-48000Hz-32bit-2.93Hz-24000Hz.wav
WARNING:tensorflow:From C:\Users\dvenk\Documents\GitHub\Impulcifer\venv\lib\site-packages\tensorflow_core\python\compat\v2_compat.py:65: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
(venv)

**Comment by jaakkopasanen** [comment]
I came up with a clever solution and moved Tensorflow import into the biquad filter optimization function in AutoEQ. Biquad filters are not optimized in Impulcifer so now the warning is gone. Impulcifer runs a bit faster too.
