### ISSUE TITLE
7.1 Sweet Creation Error due to --length

### ISSUE THREAD

**Issue by rpx91** [jaakkopasanen/Impulcifer#31]
Small error - you just need to remove the reference to length in the [Wiki ](https://github.com/jaakkopasanen/Impulcifer/wiki/Measurements)and it outputs fine.

`impulse_response_estimator.py: error: unrecognized arguments: --length=5`

**Comment by jaakkopasanen** [comment]
The parameter name was `--duration` all along and it works as intended.
