### ISSUE TITLE
Suggestion: Amplify/Normalize HRIR

### ISSUE THREAD

**Issue by rpx91** [jaakkopasanen/Impulcifer#33]
My HRIR has a very low volume relative to others that ship with HeSuVi. I can fix this via applying a 13db boost in peace. The problem with that method is that I then can't A vs B the other HRIR's because they're much too loud.

Would it be possible to normalise the level so that it matches the default ones in HeSuVi?

**Comment by arkserg** [comment]
> My HRIR has a very low volume relative to others that ship with HeSuVi. I can fix this via applying a 13db boost in peace. The problem with that method is that I then can't A vs B the other HRIR's because they're much too loud.
> 
> Would it be possible to normalise the level so that it matches the default ones in HeSuVi?

I actually have the same issue: my HRIR has a very low volume. I don't need to compare it to other filter though, but even when maximum amplification in HeSuVi applied I have to set my amplifier to maximum to get desired sound level.
I can't get higher volume on my speakers recording without some spikes go outside allowed range (clipping I gas).

**Comment by rpx91** [comment]
You can amplify in Audacity manually - just highlight all tracks and click Effect amplify.

But it would be nice to aim for a target for ease of use.

**Comment by arkserg** [comment]
Amplify my recordings? As I already mentioned, i have some spikes on recording, witch are almost 'touch' the ceiling, and I afraid, that further amplification will cause clipping and incorrect HRIR calculation.

**Comment by rpx91** [comment]
Ah ok. To fix mine all I did was import the generated hesuvi.wav into Audacity to amplify that. But I didn't have any clipping on mine.

**Comment by arkserg** [comment]
Actually it could work. I never tried to import hesuvi.wav into Audacity, I was talking about speaker measurements that I made. Thank you, gonna try it today.

**Comment by jaakkopasanen** [comment]
I could add `--preamp` parameter which amplifies the result peak gain to that value eg `--preamp=9` sets it to 9 dB. Of course this could lead to clipping in real-time playback but can't really do anything for it but leave the responsibility for the user.

**Comment by rpx91** [comment]
That'd be ideal - in all the ones I've amplified Audacity says it can boost by 20-30db with no clipping so should be safe.

**Comment by jaakkopasanen** [comment]
Peak of the impulse reponse doesn't actually tell the headroom. Reverb raises the overall volume so that even if impulse response peak is not near 0 dB the signal can still clip. You can check the resulting gain in EqualizerAPO configuration editor, that has a frequency response graph which should tell you that the peak gain at any frequency is 0 dB for HRIRs created with Impulcifer.

**Comment by arkserg** [comment]
> You can check the resulting gain in EqualizerAPO configuration editor, that has a frequency response graph which should tell you that the peak gain at any frequency is 0 dB for HRIRs created with Impulcifer
Mine was normalized to -6.6 dB, not 0, so I Amplified hesuvi.wav in Audacity.

**Comment by arkserg** [comment]
By the way, is it possible to optionally left frequencies below certain level unmodified, like 100Hz or something like this as they should not affect positioning.

**Comment by jaakkopasanen** [comment]
@arkserg Could you maybe share the recording folder you had which showed -6.6 dB in configuration editor. I'd like to debug. Are you sure you didn't have any other source of preamping enabled, such as the attenuation on HeSuVi's connection tab? I'm asking because I made this mistake myself and had a 12 dB boost in Impulcifer for a while until I realized that I had attenuation of 12 dB in HeSuVi.

**Comment by arkserg** [comment]
Ok, I will provide my folder this evening and also check attenuation. I almost sure that I didn't do anything, but maybe there are some settings enabled by default.

**Comment by arkserg** [comment]
https://drive.google.com/open?id=1pguzazUDCYJ0aOvH4RCb6x_t2vg_HGO8

**Comment by venkatesh63** [comment]
@jaakkopasanen i already said to you hesuvi.wav getting very low noise in virtulization tab. after the executing the demo. @arkserg downloaded the files rectify the errors.

**Comment by jaakkopasanen** [comment]
@arkserg Headroom in your measurements is 6 dB for left channel and 0 dB for right channel so the normalization works as intended.

**Comment by jaakkopasanen** [comment]
Level adjustment has been implemented. See here: https://github.com/jaakkopasanen/Impulcifer#level-adjustment
