### ISSUE TITLE
Scipy build failure

### ISSUE THREAD

**Issue by arkserg** [jaakkopasanen/Impulcifer#34]
Tried on two different windows pcs and in docker, same error:

    ERROR: Command errored out with exit status 1:
     command: /usr/src/app/venv/bin/python /usr/src/app/venv/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpln8nwj0i
         cwd: /tmp/pip-install-z9zxmnlc/scipy
    Complete output (153 lines):
    lapack_opt_info:
    lapack_mkl_info:
    customize UnixCCompiler
      libraries mkl_rt not found in ['/usr/src/app/venv/lib', '/usr/local/lib', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
      NOT AVAILABLE

    openblas_lapack_info:
    customize UnixCCompiler
    customize UnixCCompiler
      libraries openblas not found in ['/usr/src/app/venv/lib', '/usr/local/lib', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
      NOT AVAILABLE

    openblas_clapack_info:
    customize UnixCCompiler
    customize UnixCCompiler
      libraries openblas,lapack not found in ['/usr/src/app/venv/lib', '/usr/local/lib', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
      NOT AVAILABLE

**Comment by arkserg** [comment]
Solved by switching from python 3.8.0 to python 3.7.4

**Comment by jaakkopasanen** [comment]
Thanks a lot for the issue and especially the solution. I added a mention that Python 3.8 doesn't work to install instructions.
