### ISSUE TITLE
New error after the last update

### ISSUE THREAD

**Issue by PhilHiTech** [jaakkopasanen/Impulcifer#41]
this error appears both in demo but also with my hrir
Win10 x64, Python 3.7.5

`(venv) C:\ProgramsPortable\Impulcifer>python impulcifer.py --test_signal=D:\I\Impulcifer_Data\sweep-6.15s-48000Hz-32bit-2.93Hz-24000Hz.pkl --room_mic_calibration=D:\I\Impulcifer_Data\demo\room-mic-calibration.txt --room_target=D:\I\Impulcifer_Data\harman-room-target.csv --dir_path=D:\I\Impulcifer_Data\demo --plot`

`Traceback (most recent call last):`
`  File "impulcifer.py", line 494, in <module>`
`    main(**create_cli())`
`  File "impulcifer.py", line 94, in main`
`    plot=plot`
`  File "impulcifer.py", line 223, in correct_room`
`    fr.raw -= room_mic_calibration.raw`
`AttributeError: 'str' object has no attribute 'raw'`

**Comment by jaakkopasanen** [comment]
Thanks a lot for reporting. It's fixed now. Could you test and close the issue if it has been solved for you?

**Comment by PhilHiTech** [comment]
Many thanks! No more errors appear, but when I process my recordings, the left speaker post plots show a null amplitude, unlike the results shown for the demo recording...

Why? ... should I redo the recordings?
What do you think about it?

**Comment by jaakkopasanen** [comment]
Hmm, interesting. Could you share the plots or the whole recording folder here with me so I can take a look? You can simply drag and drop files to the comment field and Github will handle it.

**Comment by PhilHiTech** [comment]
[plots.zip](https://github.com/jaakkopasanen/Impulcifer/files/3883677/plots.zip)
I recorded the room files with this setting:
`--channels = 1`
... could this be the reason for plots with zero amplitude?

**Comment by PhilHiTech** [comment]
My Scarlett 2i2 always records two channels, so I have to use the setting `--channels = 1` ...

**Comment by jaakkopasanen** [comment]
The pre and room plots look correct but the post plots definitely have that -40 dB for left side. Can't really say more from the plots. I would guess this is a glitch.

Please share the all the recordings and mic calibration files too and I'll try debug this.

**Comment by PhilHiTech** [comment]
Thank you very much for your availability!

My recordings folder link e my room-mic-calibration.txt
[](https://drive.google.com/open?id=1J6PQ-N4gOH_2PjBTuqnGN7WrbiM0al1n)
[cal.txt](https://github.com/jaakkopasanen/Impulcifer/files/3883782/cal.txt)

**Comment by PhilHiTech** [comment]
I realized now that they are -30 dB amplitude for the demo hrir.wav and also for my hrir.wav...

**Comment by jaakkopasanen** [comment]
So the level difference problem exists in the demo files and results as well? I don't have this myself and I use the demo results myself as my daily driver so the channel balance in those is definitely correct. Could you share the generated demo plots? Also could you share your recording files so I could try to run Impulcifer on those?

**Comment by PhilHiTech** [comment]
[demo_hrir.zip](https://github.com/jaakkopasanen/Impulcifer/files/4007970/demo_hrir.zip)
[DaytonEmm6_Cal.txt](https://github.com/jaakkopasanen/Impulcifer/files/4007977/DaytonEmm6_Cal.txt)
[my_hrir-recordings.7z](https://drive.google.com/file/d/1sXuawUgr_52C_JElDGUS37Tcw6bW203k/view?usp=sharing)

**Comment by PhilHiTech** [comment]
[plots.zip](https://github.com/jaakkopasanen/Impulcifer/files/4007994/plots.zip)
[my_hrir](https://drive.google.com/file/d/1MNnHygmTT-hbFSerfmASNj6ddeQgeTi8/view?usp=sharing)

**Comment by jaakkopasanen** [comment]
demo_hrir.zip contains HRIR WAV file while I need the demo plots. Actually it would be better if you shared the whole demo folder with all the results and plots.

**Comment by jaakkopasanen** [comment]
I tried running Impulcifer with your recordings but it seems the recordings are 96 kHz. Did you actually measure them at 96 kHz? If so could you also share the test signal WAV or PKL file with me?

**Comment by PhilHiTech** [comment]
Yes, I recorded at 96 KHz.
[sweep-seg-96k.7z](https://drive.google.com/open?id=1gSANmMuznbKfGmluewFz17YUGBfDy9Ki)

**Comment by PhilHiTech** [comment]
[demo_plots.7z](https://drive.google.com/open?id=1lwDtVK8AdhbHiAcC0f3EtvVa9jEI7LAo)
[demo_hrir-results.7z](https://drive.google.com/open?id=1PnWbMm32qQqQRhrannCDngnSSUe6YDLq)

**Comment by PhilHiTech** [comment]
The demo's working now, but there's 24dB of headroom...

**Comment by jaakkopasanen** [comment]
Demo plots look about right. Do you have the hesuvi.wav available, I'd like to confirm the results by listening to it?

Where did you get the 24 dB from?

**Comment by PhilHiTech** [comment]
I got the value from Audacity

**Comment by jaakkopasanen** [comment]
I ran your recordings. I get a bit over 4 dB of headroom. Channel balance is good.

I'm not sure why the peak isn't at 0 dB. I've never done 96 kHz recordings before. Could be related to that.

**Comment by jaakkopasanen** [comment]
You shouldn't look at the values of the impulse responses. They don't tell the truth about headroom. Having a reverberation tail in the impulse response increases the total loudness and can even increase it past 0 dB. The real headroom must be read from FFT when all left side IRs have been summed together (and right side IRs together). It's the peak value of the summed FFT.

**Comment by PhilHiTech** [comment]
Okay, my mistake... I thought we should just consider this:
![Audacity](https://user-images.githubusercontent.com/57483887/71559539-9c413400-2a5f-11ea-90c3-1cfcf1a396f1.jpg)

**Comment by jaakkopasanen** [comment]
I solved the 4 dB headroom mystery. Resampling impulse response to a different sampling rate (from 96 kHz to 48 kHz in this case) changes the headroom. I just added another normalization in Impulcifer to be done after resampling if resampling is used. This fixed the problem.

Have all issues been solved now for you? If so, could you close this issue.

**Comment by PhilHiTech** [comment]
> 
> 
> I ran your recordings. I get a bit over 4 dB of headroom. Channel balance is good.
> 
> I'm not sure why the peak isn't at 0 dB. I've never done 96 kHz recordings before. Could be related to that.

OK... mmmh... boh!
The plots I sent you, as you can see, show that there is actually an imbalance between the two channels, so the only way to correct this problem is to use channel-balance mids.
The point is that I'm getting a different result from yours, and I can't understand why.

**Comment by PhilHiTech** [comment]
> 
> 
> I solved the 4 dB headroom mystery. Resampling impulse response to a different sampling rate (from 96 kHz to 48 kHz in this case) changes the headroom. I just added another normalization in Impulcifer to be done after resampling if resampling is used. This fixed the problem.
> 
> Have all issues been solved now for you? If so, could you close this ticket.

OK! ... I'm gonna try hrirs again.

**Comment by jaakkopasanen** [comment]
I do get minor channel balance problems with demo recording. I just use `--channel_balance=trend` which fixes it. This is one of the greatest mysteries I'm facing with Impulcifer because in theory this should not be needed but yet it is. I've spent quite a lot of time trying to figure out the reason for it but have not solved it yet. Some users are not experiencing the problem at all. I made HRIR measurement for my friend a while ago and those results have channel balance bang on.

**Comment by PhilHiTech** [comment]
In fact I tried different channel-balance settings on different recordings, and the only one that always worked was `--channel_balance=mids`

**Comment by jaakkopasanen** [comment]
Hmm, okay. They're all pretty wild heuristic solutions so I cannot guarantee them working perfectly every time. That's why there are options.

**Comment by PhilHiTech** [comment]
![results](https://user-images.githubusercontent.com/57483887/71560209-0a3d2980-2a67-11ea-85b2-e1578dab9a4c.png)
now the plots are fine
thanks!

**Comment by jaakkopasanen** [comment]
Great! Thanks for your cooperation.
