### ISSUE TITLE
Room Correction causes bass bleed into other (virtual) channels

### ISSUE THREAD

**Issue by rpx91** [jaakkopasanen/Impulcifer#42]
My usual recording consists of replicating my real surround system that uses LS0's and a sub. Virtual Room correction on that works fine.

Yesterday I tried to measure only my LS50's in "pure direct" mode - so no subwoofer for the bass. 

When I ran the room correction on a channel ID test for the front channels you could hear an odd echo from the side or rear channels. I thought this might be a recording error so I re-ran. Same issue.

Without virtual room correction this goes away. I suspect the room correction is boosting above 80hz frequencies too much which confuses the HRTF. The issue does not manifest when I'm taking recordings at around 4-6 feet, likely cause the LS50's can produce enough bass even without a boundary but when I move back, the echo's there.

10mb was the max file size on Git so I uploaded to [Google](https://drive.google.com/open?id=1Or9Ai-Y2WunVk3-3We_tIGL13m4OpTxa) and the channel ID check is [here ](https://drive.google.com/open?id=1cDbMqRGDGEUKc-0tid-s7jQLdhj_sE39)

**Comment by jaakkopasanen** [comment]
I have this as well. I got couple of ideas how to go about it. I'll report back here when I have some results.

**Comment by jaakkopasanen** [comment]
This is solved by reverberation management as we discussed in the head-fi thread. Progrees for that can be tracked in issues #9 and #10
