### ISSUE TITLE
Can You make a software of Impulcifer

### ISSUE THREAD

**Issue by ghost** [jaakkopasanen/Impulcifer#45]
@jaakkopasanen i don't want to use/install  HeSuVi. i want to compile hesuvi.wav and hrir.wav in impulcifer only.

**Comment by jaakkopasanen** [comment]
This is way out of scope for Impulcifer so I have no intentions of making Impulcifer anything else but a tool for measuring HRIRs. What is the problem with HeSuVi you would like to be solved with having Impulcifer as a standalone software?
