### ISSUE TITLE
New Error since Update

### ISSUE THREAD

**Issue by rpx91** [jaakkopasanen/Impulcifer#47]
Tried to do a new recording today and getting the following error when trying to process recordings. I am using --no_room_correction. Seems to be related to the most recent update.

```
(venv) C:\Users\dushy\Impulcifer>python impulcifer.py --test_signal="data/sweep-6.15s-48000Hz-32bit-2.93Hz-24000Hz.pkl" --dir_path="data/my_hrir" --no_room_correction
Traceback (most recent call last):
  File "impulcifer.py", line 494, in <module>
    main(**create_cli())
  File "impulcifer.py", line 71, in main
    target = create_target(estimator, bass_boost_gain, bass_boost_fc, bass_boost_q, tilt)
  File "impulcifer.py", line 325, in create_target
    target.raw = target.create_target(
AttributeError: 'FrequencyResponse' object has no attribute 'create_target'
```

When I revert back to the previous commit with git checkout recordings process fine

Weirdly on a completely fresh install it works fine.

**Comment by jaakkopasanen** [comment]
Maybe you forgot to update Python dependencies with `pip install -U -r requirements.txt`? I have updated the AutoEQ version in Impulcifer to a newer one which has that `create_target()` function.

**Comment by rpx91** [comment]
Oh dammit, I forgot that. I'll add it to my list of commands I save. Hard remembering everything when you take a couple months between recordings.
