### ISSUE TITLE
Support for mic_calibration.py

### ISSUE THREAD

**Issue by PhilHiTech** [jaakkopasanen/Impulcifer#48]
How can the calibration of binaural microphones ( right-mic-calibration.csv and left-mic-calibration.csv files from `mic_calibration.py` ) in Impulcifer be accounted for?

**Comment by jaakkopasanen** [comment]
At the moment there's no compensation for the binaural mic frequency response, only for the room measurement mic. This is because the headphone compensation will compensate for the binaural mics' frequency response also.
