### ISSUE TITLE
Could not install `requirements.txt` - Problem with `tensorflow~=2.0.0`

### ISSUE THREAD

**Issue by FlorianKempenich** [jaakkopasanen/Impulcifer#49]
Hi,

I'm so excited you created this project. This is amazing 😍 I was on the fence to save and try to get a used realizer a16 somewhere. But **this** . . . 😍

So before buying all the equipement I wanted to check out the demo to see how close it'd sound to something like OOYH.

Unfortunately when installing the dependencies I get an error:
```
ERROR: Could not find a version that satisfies the requirement tensorflow~=2.0.0 (from autoeq==1.2.1->-r requirements.txt (line 9)) (from versions: 2.2.0rc3, 2.2.0rc4, 2.2.0)
ERROR: No matching distribution found for tensorflow~=2.0.0 (from autoeq==1.2.1->-r requirements.txt (line 9))
```

I tried to fork `autoeq-pkg` and manually update tensorflow to version `2.2.0`. But then I kept having problem with other dependencies ...
... so I figured I'd create an issue 🙂

If you need me to run any test, just let me know 🙂👍
And, once again, thank you for your work 😍

**Comment by jaakkopasanen** [comment]
Very glad to hear you're so excited about this! What version of Python are you running? Typically this has been an issue with Python versions.

**Comment by FlorianKempenich** [comment]
Thanks for the prompt response. I'm using python `3.8`. Which version are you using? 

Haha . . . I just did a search on the `README` to see if you mention something about python versions and ... I've just noticed
> Download and install 64-bit Python 3. **Python 3.8 doesn't work yet**. Make sure to check Add Python 3 to PATH.

😅

I'll try with python `3.7` now I'll let you know how it went in a sec 🙂

**Comment by FlorianKempenich** [comment]
I works 😃
I'm closing this.
