### ISSUE TITLE
Headphone Transform EQ Error

### ISSUE THREAD

**Issue by rpx91** [jaakkopasanen/Impulcifer#50]
Trying to nail a transform from a Bose 700 headphone measurement to Air Pods Pro.

I ran the following command in AutoEQ:

`python autoeq.py --input_dir="C:\Users\dushy\AutoEq\oratory1990\data\earbud\Apple Airpods Pro" --output_dir="my_results/APP (Bose700) mk3" --compensation="compensation/harman_in-ear_2019v2.csv" --sound_signature="C:\Users\dushy\AutoEq\results\oratory1990\harman_over-ear_2018\Bose Noise Cancelling Headphones 700\Bose Noise Cancelling Headphones 700.csv" --equalize --parametric_eq --max_filters=5+5 --ten_band_eq --bass_boost=4`

However, Impulcifer doesn't seem to like the eq.csv output from AutoEQ and throws the following error:

```
(venv) C:\Users\dushy\Impulcifer>python impulcifer.py --test_signal="data/sweep-6.15s-48000Hz-32bit-2.93Hz-24000Hz.pkl" --dir_path="data/my_hrir" --fs=44100
Traceback (most recent call last):
  File "impulcifer.py", line 499, in <module>
    main(**create_cli())
  File "impulcifer.py", line 115, in main
    fr.error += eq.error
ValueError: operands could not be broadcast together with shapes (641,) (0,) (641,)
```

I've run other transforms fine - but I'm trying to nail a good HRIR for my Air Pods Pro so experimenting with different headphones and measurement sources. This particular one is throwing that error.

I've uploaded the eq.csv [here](https://drive.google.com/file/d/1JMg6XroTNIuq3bmKv3kq5Fuw0zR7F4aN/view?usp=sharing)

**Comment by rpx91** [comment]
Ignore this - I had the command wrong in AutoEQ anyway. When I run them now they all work.

**Comment by rpx91** [comment]
Getting this error again on a couple of other headphones I've been trying.

In running this command in autoEQ to make a HRIR for the Air Pods Pro using a Creative Aurvana Live recording:

`python autoeq.py --input_dir="C:\Users\dushy\AutoEq\oratory1990\data\earbud\Apple Airpods Pro" --output_dir="my_results/APP (Aurvana)" --compensation="compensation/harman_over-ear_2018_wo_bass.csv" --sound_signature="C:\Users\dushy\AutoEq\results\oratory1990\harman_over-ear_2018\Creative Aurvana Live!\Creative Aurvana Live!.csv" --equalize --parametric_eq --max_filters=5+5 --ten_band_eq --bass_boost=4`

Exact same error

`ValueError: operands could not be broadcast together with shapes (641,) (0,) (641,)`

**Comment by jaakkopasanen** [comment]
@rpx91 are you still having these errors? I saw your comment on #14 which makes me think eq feature works for you.

**Comment by rpx91** [comment]
Hey - I've got it working fine. I do sometimes get errors like that though, depending on which headphone and which IEM I'm transforming to. Haven't had it pop up recently, which makes me think it was upstream of Impulcifer and updating the dependencies got it working again.
