### ISSUE TITLE
Using MEMS microphones

### ISSUE THREAD

**Issue by diimdeep** [jaakkopasanen/Impulcifer#56]
There is high performant very low price ($2) MEMS microphones with i2s digital output like ICS‐43434, INMP441 that can be relatively easily used with any arduino like MCU (5$) to capture output.  
I think it is very cheap and performant way to capture BRIR, although requires more friction with connecting it ti MCU and little programming. 

What do you think ? 

Here is specs:

![Screenshot 2021-04-12 at 11 02 27](https://user-images.githubusercontent.com/485713/114361338-b2083900-9b7e-11eb-9259-af4c58e735ca.png)

[INMP441.pdf](https://github.com/jaakkopasanen/Impulcifer/files/6294906/INMP441.pdf)
[ICS‐43434.pdf](https://github.com/jaakkopasanen/Impulcifer/files/6294908/ICS.43434.pdf)

**Comment by jaakkopasanen** [comment]
The signal to noise ratio and bandwidth don't look too amazing. They're cheap, I give you that, assuming you don't value your time / are interested in the DIYing.

Not really anything to do here so I'll close the issue.
