### ISSUE TITLE
Processing Fails.

### ISSUE THREAD

**Issue by JustCauseWhyNot** [jaakkopasanen/Impulcifer#68]
I'm running into an issue. I've had quite a few issues getting to this point, but I've resolved them until now. I don't know how to fix this issue.

<details>

```py
❯ python recorder.py --play="data/sweep-seg-FL,FR-stereo-6.15s-48000Hz-32bit-2.93Hz-24000Hz.wav" --record="data/my_hrir/headphones.wav"
Traceback (most recent call last):
  File "/home/justcausewhynot/.local/bin/Impulcifer/recorder.py", line 260, in <module>
    play_and_record(**create_cli())
  File "/home/justcausewhynot/.local/bin/Impulcifer/recorder.py", line 202, in play_and_record
    input_device, output_device = get_devices(
                                  ^^^^^^^^^^^^
  File "/home/justcausewhynot/.local/bin/Impulcifer/recorder.py", line 141, in get_devices
    input_device = get_device(input_device, 'input', host_api=host_api)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/justcausewhynot/.local/bin/Impulcifer/recorder.py", line 116, in get_device
    raise DeviceNotFoundError('Could not find any device which satisfies minimum channel count.')
DeviceNotFoundError: Could not find any device which satisfies minimum channel count.
```
</details>

<details>

```py
❯ python -m sounddevice
   0 HDA NVidia: S2719DGF (hw:0,3), ALSA (0 in, 2 out)
   1 HDA NVidia: HDMI 1 (hw:0,7), ALSA (0 in, 8 out)
   2 HDA NVidia: HDMI 2 (hw:0,8), ALSA (0 in, 8 out)
   3 HDA NVidia: HDMI 3 (hw:0,9), ALSA (0 in, 8 out)
   4 HD-Audio Generic: ALC892 Analog (hw:1,0), ALSA (2 in, 2 out)
   5 HD-Audio Generic: ALC892 Alt Analog (hw:1,2), ALSA (2 in, 0 out)
   6 sysdefault, ALSA (128 in, 128 out)
   7 front, ALSA (0 in, 2 out)
   8 surround40, ALSA (0 in, 2 out)
   9 surround51, ALSA (0 in, 2 out)
  10 surround71, ALSA (0 in, 2 out)
  11 pipewire, ALSA (64 in, 64 out)
  12 dmix, ALSA (0 in, 2 out)
* 13 default, ALSA (64 in, 64 out)
```
</details>

**Comment by jaakkopasanen** [comment]
Which audio interface are you using?

**Comment by JustCauseWhyNot** [comment]
I am using a motu m2

**Comment by jaakkopasanen** [comment]
Something about sounddevice not recognizing the M2. You are able to use it to record in other applications, right? I see ALSA devices, you're on Linux, right?

**Comment by JustCauseWhyNot** [comment]
Yes for all.

**Comment by JustCauseWhyNot** [comment]
I've changed my default alsa card in `/etc/asound.conf` to the correct index for the motu m2. Unfortunately that didn't seem to cause any difference in terms of fixing the problem. I'm really confused as to why this problem is occurring.

**Comment by JustCauseWhyNot** [comment]
I'm trying to rebuild impulcifer, and making sure I follow instructions thoroughly. But when I try and run `pip install -U -r requirments.txt` it fails every time with, and here is a [link](https://gist.github.com/JustCauseWhyNot/fc7633e8f422477226456200c0abd48a) to full output
```py
      Failed to build numpy
      ERROR: Could not build wheels for numpy, which is required to install pyproject.toml-based projects
```
I've made sure to install python3.8, because I'm using gentoo it installs python for portage. But the python versions included have moved on past 3.8, and if I understand correctly the minimum python version supported by portage is python3_10.

**Comment by JustCauseWhyNot** [comment]
Ok I was able to fix that issue, but the original issue still exists.

**Comment by JustCauseWhyNot** [comment]
I've gotten past that hurdle now by running 
```py
python3.8 recorder.py --play="data/sweep-seg-FL,FR-stereo-6.15s-48000Hz-32bit-2.93Hz-24000Hz.wav" --record="data/my_hrir/headphones.wav" --host_api=alsa --output_device=pipewire --input_device=pipewire
```

At this point though I'm having yet another problem. When I try, and run 
```py 
python3.8 recorder.py --play="data/sweep-seg-FL,FC,FR,SR,BR,BL,SL-7.1-6.15s-48000Hz-32bit-2.93Hz-24000Hz.wav" --record="data/my_hrir/FL,FC,FR,SR,BR,BL,SL.wav" --host_api=alsa --output_device=pipewire --input_device=pipewire
```

I get output of 
```
Traceback (most recent call last):
  File "recorder.py", line 260, in <module>
    play_and_record(**create_cli())
  File "recorder.py", line 198, in play_and_record
    fs, data = read_wav(play)
  File "/home/justcausewhynot/.local/bin/Impulcifer/utils.py", line 23, in read_wav
    raise FileNotFoundError(f'File in path "{os.path.abspath(file_path)}" does not exist.')
FileNotFoundError: File in path "/home/justcausewhynot/.local/bin/Impulcifer/data/sweep-seg-FL,FC,FR,SR,BR,BL,SL-7.1-6.15s-48000Hz-32bit-2.93Hz-24000Hz.wav" does not exist.
```

**Comment by JustCauseWhyNot** [comment]
I'd just like to clarify is that I'm trying to create a 7.1 surround sound personalized wav file for that if I understand correctly will also include autoeq in the file itself.

**Comment by JustCauseWhyNot** [comment]
I really want to get impulcifer to work, and I've tried to get it to work. But I'm getting blocked with the above value error. Any help would be grearly appreciated.

**Comment by JustCauseWhyNot** [comment]
Ok right now I'm getting a new error.

```
❯ python impulcifer.py --test_signal=data/sweep-6.15s-48000Hz-32bit-2.93Hz-24000Hz.pkl --dir_path=/home/justcausewhynot/.local/bin/Impulcifer/data/my_hrir --plot
Creating impulse response estimator...
Running room correction...
Running headphone compensation...
Creating headphone equalization...
Creating frequency response target...
Opening binaural measurements...
Traceback (most recent call last):
  File "impulcifer.py", line 556, in <module>
    main(**create_cli())
  File "impulcifer.py", line 81, in main
    hrir = open_binaural_measurements(estimator, dir_path)
  File "impulcifer.py", line 388, in open_binaural_measurements
    raise ValueError('No HRIR recordings found in the directory.')
ValueError: No HRIR recordings found in the directory.
```
Even though I very much do have wav files in the data/my_hrir dir.

**Comment by JustCauseWhyNot** [comment]
I dont mean to be rude, but is rhis abandonware at this point?

**Comment by JustCauseWhyNot** [comment]
Do I need speakers in order to use impulcifer? I thought I just needed headphones, and binaural microphones.

**Comment by JustCauseWhyNot** [comment]
I'll just close this issue for now. Let me know if I'm wrong about needing speakers in order to use impulcifer.

**Comment by jaakkopasanen** [comment]
You indeed need speakers. The whole purpose of Impulcifer is to measure the transfer function from speakers to ears to replicate that with headphones.

**Comment by JustCauseWhyNot** [comment]
Appreciate the answer, and apologies for the unnecessary issue. I will get speakers eventually then.
